docs: add prerequesits
omnect/omnect-cli pull request #85
Opened 2023-09-15 12:21 UTC by empwilli

2023-09-15 12:27 UTC, mlilien approved these changes

2023-09-15 12:27 UTC, mlilien commented on README.md
> +- docker: For the `file`, `iot-hub-device-update`, `identity` and `wifi` commands.
okay. 
currently the install description implicitly has docker as a prerequisite.

2023-09-18 06:27 UTC, JanZachmann approved these changes

2023-09-28 11:29 UTC, JanZachmann requested changes
1. can you update dependencies --> #84 
2. in docker.rs we reference set_ssh_tunnel_cert.sh but I cannot find the file under backend/sh/

2023-10-04 13:59 UTC, JanZachmann approved these changes

2023-10-05 07:29 UTC, merged